---
# Mount the secrets volume
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-chains-controller
  namespace: tekton-chains
spec:
  template:
    spec:
      containers:
        - name: tekton-chains-controller
          volumeMounts:
            # Mount the secrets volume
            - mountPath: /etc/ssl/certs
              name: chains-ca-cert
      volumes:
        - name: chains-ca-cert
          secret:
            secretName: chains-ca-cert
