---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: docker.io/haproxytech/haproxy-debian@sha256:7086aaf61dfe7f07fa36eafd4bb567a60564f7dd6fcf7cdafdfbbab19c01f0ba
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - name: http-port
              protocol: TCP
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
              readOnly: true
          livenessProbe:
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 0
            timeoutSeconds: 1
            tcpSocket:
              port: 80
            periodSeconds: 10
          startupProbe:
            failureThreshold: 20
            successThreshold: 1
            initialDelaySeconds: 0
            timeoutSeconds: 1
            tcpSocket:
              port: 80
            periodSeconds: 1
          readinessProbe:
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 0
            timeoutSeconds: 1
            tcpSocket:
              port: 80
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: haproxy-config
