---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    global
        maxconn 20000
        nbthread 2

    defaults
        maxconn 20000
        timeout connect 5s
        timeout client 30s
        timeout client-fin 1s
        timeout server 30s
        timeout server-fin 1s
        timeout http-request 10s
        timeout http-keep-alive 300s
        timeout check 10s

    frontend fe_el_pac_http
        bind :8080
        mode http
        tcp-request inspect-delay 5s
        tcp-request content accept if HTTP

        acl PATH_pac path_beg -i /pac/
        use_backend be_el_pac if PATH_pac

    backend be_el_pac
        mode http
        option redispatch
        option forwardfor
        timeout check 5000ms
        server el-pac el-pipelines-as-code-interceptor.openshift-pipelines.svc.cluster.local:8080
