---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
images:
  - name: quay.io/redhat-pipeline-service/settings-operator
    newName: quay.io/redhat-pipeline-service/settings-operator
    newTag: latest
namespace: settings-pipeline-service-controller
