apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - plnsvc-manager.yaml
  - https://raw.githubusercontent.com/tektoncd/pipeline/v0.32.0/config/100-namespace.yaml
