---
apiVersion: v1
kind: Service
metadata:
  name: pipelines-as-code-controller
  namespace: pipelines-as-code
  labels:
    app: pipelines-as-code-controller
spec:
  ports:
    - name: http-metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
