---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: "build"

resources:
  - allow-argocd.yaml
  - https://github.com/openshift-pipelines/pipelines-as-code/releases/download/v0.16.0/release.yaml

patchesStrategicMerge:
  - disable-pipelines-as-code-webhook.yaml

patchesJson6902:
  - target:
      kind: Namespace
      name: pipelines-as-code
    patch: |-
      - op: add
        path: "/metadata/labels"
        value:
          argocd.argoproj.io/managed-by: openshift-gitops
  - target:
      kind: Deployment
      name: pipelines-as-code-controller
      namespace: pipelines-as-code
    patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/image"
        value:
          registry.redhat.io/openshift-pipelines/pipelines-pipelines-as-code-rhel8:v1.10.0-6
  - target:
      kind: Deployment
      name: pipelines-as-code-watcher
      namespace: pipelines-as-code
    patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/image"
        value:
          registry.redhat.io/openshift-pipelines/pipelines-pipelines-as-code-rhel8:v1.10.0-6
  - target:
      kind: Deployment
      name: pipelines-as-code-webhook
      namespace: pipelines-as-code
    patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/image"
        value:
          registry.redhat.io/openshift-pipelines/pipelines-pipelines-as-code-rhel8:v1.10.0-6
