---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: "build"

resources:
  - allow-argocd.yaml
  - https://github.com/openshift-pipelines/pipelines-as-code/releases/download/v0.17.0/release.yaml

patchesStrategicMerge:
  - disable-pipelines-as-code-webhook.yaml

patchesJson6902:
  - target:
      kind: Namespace
      name: pipelines-as-code
    patch: |-
      - op: add
        path: "/metadata/labels"
        value:
          argocd.argoproj.io/managed-by: openshift-gitops
