---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: "build"

resources:
  - allow-argocd.yaml
  - https://github.com/openshift-pipelines/pipelines-as-code/releases/download/v0.16.0/release.yaml

# TODO backing off until https://issues.redhat.com/browse/SRVKP-3134 is resolved
# images:
#  - name: ghcr.io/openshift-pipelines/pipelines-as-code-controller:v0.16.0
#    newName: registry.redhat.io/openshift-pipelines/pipelines-pipelines-as-code-rhel8
#    newTag: v1.10.2-1
#  - name: ghcr.io/openshift-pipelines/pipelines-as-code-watcher:v0.16.0
#    newName: registry.redhat.io/openshift-pipelines/pipelines-pipelines-as-code-rhel8
#    newTag: v1.10.2-1
#  - name: ghcr.io/openshift-pipelines/pipelines-as-code-webhook:v0.16.0
#    newName: registry.redhat.io/openshift-pipelines/pipelines-pipelines-as-code-rhel8
#    newTag: v1.10.2-1

patchesStrategicMerge:
  - disable-pipelines-as-code-webhook.yaml
  - controller-sync.yaml
  - watcher-sync.yaml
  - controller-service-update.yaml

patchesJson6902:
  - target:
      kind: Namespace
      name: pipelines-as-code
    patch: |-
      - op: add
        path: "/metadata/labels"
        value:
          argocd.argoproj.io/managed-by: openshift-gitops
