---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-service-exporter-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipeline-service-exporter-reader
subjects:
  - kind: ServiceAccount
    name: pipeline-service-exporter
    namespace: openshift-pipelines
