---
resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml

images:
  - name: quay.io/redhat-appstudio/pipeline-service-exporter
    newName: quay.io/redhat-appstudio/pipeline-service-exporter
    newTag: 2782659983c94692497467cd1cf952b1bc1f0da4

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
