---
resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml

images:
  - name: quay.io/konflux-ci/pipeline-service-exporter
    newName: quay.io/konflux-ci/pipeline-service-exporter
    newTag: 95fe19bf616c628e6e8f30487113b61861569a6e

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
