---
resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml

images:
  - name: quay.io/redhat-appstudio/pipeline-service-exporter
    newName: quay.io/redhat-appstudio/pipeline-service-exporter
    newTag: cdff9b19bf4b6e7009412ae6103be882a3a36f9b

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
