---
resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml

images:
  - name: quay.io/redhat-appstudio/pipeline-service-exporter
    newName: quay.io/redhat-appstudio/pipeline-service-exporter
    newTag: ee511e79117e5abaa651b150c27038bdb82834c8

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
