---
resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml

images:
  - name: quay.io/redhat-appstudio/pipeline-service-exporter
    newName: quay.io/redhat-appstudio/pipeline-service-exporter
    newTag: 71521811ffef57ee563e627bb7ec4cd1f826ab94

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
