---
resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml

images:
  - name: quay.io/konflux-ci/pipeline-service-exporter
    newName: quay.io/konflux-ci/pipeline-service-exporter
    newTag: 9d2439c8a77d2ce0527cc5aea3fc6561b7671b48

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
