---
resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml

images:
  - name: quay.io/redhat-appstudio/pipeline-service-exporter
    newName: quay.io/redhat-appstudio/pipeline-service-exporter
    newTag: 7ffa67747cae05345dd1e9a274ec26c50d508068

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
