---
apiVersion: v1
kind: Service
metadata:
  name: pipeline-metrics-exporter-service
  namespace: pipeline-service
spec:
  selector:
    app: pipeline-metrics-exporter
  ports:
    - name: metrics
      path: /metrics
      port: 9117
      targetPort: 9117
      protocol: TCP
