---
apiVersion: v1
kind: Service
metadata:
  name: pipeline-metrics-exporter-service
  namespace: openshift-pipelines
spec:
  selector:
    app: pipeline-metrics-exporter
  ports:
    - name: metrics
      port: 9117
      targetPort: 9117
      protocol: TCP
