---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-manager
  namespace: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-admin
rules:
  - apiGroups:
      - ""
    resources:
      - "events"
      - "limitranges"
      - "resourcequotas"
      - "secrets"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - "configmaps"
      - "namespaces"
      - "pods"
      - "serviceaccounts"
      - "services"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources:
      - "mutatingwebhookconfigurations"
      - "validatingwebhookconfigurations"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - "customresourcedefinitions"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
  - apiGroups:
      - "apiresource.kcp.dev"
    resources:
      - "apiresourceimports"
      - "negotiatedapiresources"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "apis.kcp.dev"
    resources:
      - "apibindings"
      - "apiexports"
      - "apiresourceschemas"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "certificates.k8s.io"
    resources:
      - "certificatesigningrequests"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "flowcontrol.apiserver.k8s.io"
    resources:
      - "flowschemas"
      - "prioritylevelconfigurations"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - "clusterroles"
      - "clusterrolebindings"
      - "roles"
      - "rolebindings"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - "clusterroles"
      - "clusterrolebindings"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
  - apiGroups:
      - "tekton.dev"
    resources:
      - "conditions"
      - "pipelineresources"
      - "runs"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "triggers.tekton.dev"
    resources:
      - "clustertriggerbindings"
      - "eventlisteners"
      - "triggers"
      - "triggerbindings"
      - "triggertemplates"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "triggers.tekton.dev"
    resources:
      - "clusterinterceptors"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
  - apiGroups:
      - "workload.kcp.dev"
    resources:
      - "workloadclusters"
    verbs:
      - "get"
      - "list"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "argocd-manager-crd-admin-binding"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-admin
subjects:
  - kind: ServiceAccount
    name: argocd-manager
    namespace: argocd