---
apiVersion: v1
kind: Namespace
metadata:
  name: plnsvc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: plnsvc-manager
  namespace: plnsvc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plnsvc-admin
rules:
  - apiGroups:
      - ""
    resources:
      - "configmaps"
      - "limitranges"
      - "namespaces"
      - "secrets"
      - "serviceaccounts"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - "events"
      - "persistentvolumeclaims"
      - "pods"
      - "services"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
  - apiGroups:
      - "tekton.dev"
    resources:
      - "conditions"
      - "pipelineresources"
      - "runs"
      - "taskruns"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "tekton.dev"
    resources:
      - "pipelineruns"
      - "pipelineruns/status"
      - "taskruns"
      - "taskruns/status"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
  - apiGroups:
      - "triggers.tekton.dev"
    resources:
      - "clusterinterceptors"
      - "eventlisteners"
      - "triggerbindings"
      - "triggertemplates"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "triggers.tekton.dev"
    resources:
      - "clusterinterceptors/status"
      - "eventlisteners/status"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "plnsvc-admin-binding"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: plnsvc-admin
subjects:
  - kind: ServiceAccount
    name: plnsvc-manager
    namespace: plnsvc