---
repos:
  - repo: https://gitlab.corp.redhat.com/infosec-public/developer-workbench/tools.git
    rev: rh-pre-commit-2.0.0
    hooks:
      # If you have not run this hook on your system before, it may prompt you to
      # log in for patterns, and you will need to try again.
      #
      # Docs: https://source.redhat.com/departments/it/it-information-security/leaktk/leaktk_components/rh_pre_commit
      - id: rh-pre-commit
      # Commit-msg attestation
      # Make sure to run `rh-multi-pre-commit --hook-type commit-msg install`
      # to enable the hook.
      - id: rh-pre-commit.commit-msg
