---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-service-manager
  namespace: pipelines-as-code
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: pipeline-service-manager-token
  namespace: pipelines-as-code
  annotations:
    kubernetes.io/service-account.name: pipeline-service-manager
