---
apiVersion: v1
kind: Namespace
metadata:
  name: plnsvc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kcp-syncer
  namespace: plnsvc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kcp-syncer
rules:
  - apiGroups:
      - ""
    resources:
      - "configmaps"
      - "pods"
      - "namespaces"
      - "serviceaccounts"
      - "secrets"
    verbs:
      - "*"
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - "customresourcedefinitions"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "kcp-syncer-binding"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kcp-syncer
subjects:
  - kind: ServiceAccount
    name: kcp-syncer
    namespace: plnsvc
