---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: acceptance-tests
spec:
  params:
    - name: aws_region
    - name: repo_url
    - name: revision
    - name: target_branch
    - name: ocp_version
    - name: results_url
  timeouts:
    finally: "0h30m0s"
  workspaces:
    - name: source
    - name: tekton-results-source
    - name: shared-workspace
  tasks:
    - name: generate-cluster-name
      taskRef:
        name: generate-cluster-name
    - name: destroy-existing-cluster
      taskRef:
        name: destroy-existing-cluster
      runAfter:
        - "clone-pipeline-service-git"
      params:
        - name: region
          value: $(params.aws_region)
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: source
          workspace: source
    - name: deploy-cluster
      taskRef:
        name: deploy-cluster
      runAfter:
        - "generate-cluster-name"
        - "clone-pipeline-service-git"
      params:
        - name: cluster-name
          value: "$(tasks.generate-cluster-name.results.cluster-name)"
        - name: ocp_version
          value: $(params.ocp_version)
        - name: region
          value: $(params.aws_region)
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: source
          workspace: source
    - name: clone-pipeline-service-git
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
    - name: setup-ci-runner
      taskRef:
        name: setup-ci-runner-container
      runAfter:
        - "deploy-cluster"
      params:
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: kubeconfig-dir
          workspace: shared-workspace
        - name: source
          workspace: source
    - name: plnsvc-setup
      taskRef:
        name: pipeline-service-setup
      runAfter:
        - "setup-ci-runner"
      workspaces:
        - name: kubeconfig-dir
          workspace: shared-workspace
        - name: source
          workspace: source
      params:
        - name: repo_url
          value: $(params.repo_url)
        - name: target_branch
          value: $(params.target_branch)
        - name: test_branch
          value: $(params.revision)
    - name: pipeline-service-tests
      taskRef:
        name: pipeline-service-tests
      runAfter:
        - "plnsvc-setup"
      params:
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: kubeconfig-dir
          workspace: shared-workspace
        - name: source
          workspace: source
    - name: tekton-results-fetch-sha
      taskRef:
        name: tekton-results-fetch-sha
      runAfter:
        - "clone-pipeline-service-git"
      params:
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: source
          workspace: source
    - name: tekton-results-upstream-e2e
      taskRef:
        name: tekton-results-upstream-e2e
      runAfter:
        - "tekton-results-fetch-sha"
        - "plnsvc-setup"
      params:
        - name: target_branch
          value: $(params.target_branch)
        - name: repo_url
          value: "$(params.results_url)"
        - name: revision
          value: "$(tasks.tekton-results-fetch-sha.results.tekton-results-downstream-sha)"
      workspaces:
        - name: source
          workspace: tekton-results-source
        - name: kubeconfig-dir
          workspace: shared-workspace
  finally:
    - name: destroy-cluster
      taskRef:
        name: destroy-cluster
      when:
        - input: "$(tasks.deploy-cluster.status)"
          operator: notin
          values: ["None", "Failed"]
      params:
        - name: cluster-name
          value: "$(tasks.generate-cluster-name.results.cluster-name)"
        - name: region
          value: $(params.aws_region)
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: source
          workspace: source
