---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: acceptance-tests
spec:
  params:
    - name: aws_region
    - name: repo_url
    - name: revision
    - name: target_branch
    - name: ocp_version
  timeouts:
    finally: "0h30m0s"
  workspaces:
    - name: source
    - name: shared-workspace
  tasks:
    - name: clone-pipeline-service-git
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
    - name: generate-cluster-name
      taskRef:
        name: generate-cluster-name
    - name: destroy-existing-cluster
      taskRef:
        name: destroy-existing-cluster
      runAfter:
        - "clone-pipeline-service-git"
      params:
        - name: region
          value: $(params.aws_region)
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: source
          workspace: source
    - name: deploy-cluster
      taskRef:
        name: deploy-cluster
      runAfter:
        - "generate-cluster-name"
        - "clone-pipeline-service-git"
      params:
        - name: cluster-name
          value: "$(tasks.generate-cluster-name.results.cluster-name)"
        - name: ocp_version
          value: $(params.ocp_version)
        - name: region
          value: $(params.aws_region)
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: source
          workspace: source
    - name: setup-ci-runner
      taskRef:
        name: setup-ci-runner-container
      runAfter:
        - "deploy-cluster"
      params:
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: kubeconfig-dir
          workspace: shared-workspace
        - name: source
          workspace: source
    - name: copy-plnsvc-code-to-ci-runner
      taskRef:
        name: copy-plnsvc-code
      runAfter:
        - "setup-ci-runner"
      params:
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: kubeconfig-dir
          workspace: shared-workspace
        - name: source
          workspace: source
    - name: plnsvc-setup
      taskRef:
        name: pipeline-service-setup
      runAfter:
        - "copy-plnsvc-code-to-ci-runner"
      workspaces:
        - name: kubeconfig-dir
          workspace: shared-workspace
        - name: source
          workspace: source
      params:
        - name: repo_url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
        - name: target_branch
          value: $(params.target_branch)
    - name: pipeline-service-tests
      taskRef:
        name: pipeline-service-tests
      runAfter:
        - "plnsvc-setup"
      params:
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: kubeconfig-dir
          workspace: shared-workspace
        - name: source
          workspace: source
  finally:
    - name: destroy-cluster
      taskRef:
        name: destroy-cluster
      when:
        - input: "$(tasks.deploy-cluster.status)"
          operator: notin
          values: ["None", "Failed"]
      params:
        - name: cluster-name
          value: "$(tasks.generate-cluster-name.results.cluster-name)"
        - name: region
          value: $(params.aws_region)
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: source
          workspace: source
