---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-pipeline-service-upgrade
spec:
  params:
    - name: repo_url
    - name: revision
    - name: target_branch
    - name: pr_title
    - name: source_branch
  timeouts:
    finally: "0h30m0s"
  workspaces:
    - name: shared-workspace
  tasks:
    - name: print-pr-title-param
      params:
        - name: pr_title
          value: $(params.pr_title)
      taskSpec:
        steps:
          - name: print-pr-title
            image: alpine
            script: |
              #!/bin/sh
              echo "=========================="
              echo "$(params.repo_url)"
              echo "=========================="
              echo "$(params.pr_title)"
              echo "=========================="
              echo "$(params.revision)"
              echo "=========================="
              echo {{ body.pull_request.title }}
              echo "=========================="
              echo "$(params.source_branch)"
              echo "=========================="
    - name: should-be-skipped
      taskSpec:
        steps:
          - name: print-something
            image: alpine
            script: |
              #!/bin/sh
              echo "=========================="
              echo "this should not be printed"
              echo "=========================="
      when:
        - input: "$(params.source_branch)"
          operator: notin
          values: ["fix-nightly-skip-downgrade"]
      runAfter:
        - "print-pr-title-param"
