---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-rhtap-e2e
spec:
  timeouts:
    finally: "0h30m0s"
  params:
    - name: repo_url
    - name: revision
    - name: repo_owner
    - name: target_branch
  workspaces:
    - name: workdir
  tasks:
    - name: clone-pipeline-service-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: workdir
      params:
        - name: url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
    - name: generate-cluster-name
      runAfter:
        - "clone-pipeline-service-repository"
      taskRef:
        name: generate-cluster-name
    - name: deploy-cluster
      runAfter:
        - "generate-cluster-name"
      params:
        - name: cluster-name
          value: "$(tasks.generate-cluster-name.results.cluster-name)"
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: output
          workspace: shared-workspace
      taskRef:
        name: deploy-cluster
    - name: run-rhtap-e2e
      runAfter:
        - "deploy-cluster"
      workspaces:
        - name: workdir
          workspace: shared-workspace
      params:
        - name: repo_url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
        - name: repo_owner
          value: $(params.repo_owner)
        - name: target_branch
          value: $(params.target_branch)
      taskRef:
        name: run-rhtap-e2e
  finally:
    - name: destroy-cluster
      taskRef:
        name: destroy-cluster
      when:
        - input: "$(tasks.deploy-cluster.status)"
          operator: notin
          values: ["None"]
      params:
        - name: cluster-name
          value: "$(tasks.generate-cluster-name.results.cluster-name)"
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: workdir
          workspace: shared-workspace
