---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-pipeline-service-upgrade
spec:
  params:
    - name: repo_url
    - name: revision
    - name: target_branch
  timeouts:
    finally: "0h30m0s"
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone-pipeline-service-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
        - name: subdirectory
          value: source
    - name: generate-cluster-name
      taskRef:
        name: generate-cluster-name
    - name: deploy-cluster
      taskRef:
        name: deploy-cluster
      runAfter:
        - "generate-cluster-name"
        - "clone-pipeline-service-repository"
      params:
        - name: cluster-name
          value: "$(tasks.generate-cluster-name.results.cluster-name)"
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: workdir
          workspace: shared-workspace
    - name: setup-ci-runner-container
      taskRef:
        name: setup-ci-runner-container
      runAfter:
        - "deploy-cluster"
      retries: 2
      params:
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: workdir
          workspace: shared-workspace
    - name: deploy-pipeline-service-baseline
      taskRef:
        name: deploy-pipeline-service
      runAfter:
        - "setup-ci-runner-container"
      workspaces:
        - name: workdir
          workspace: shared-workspace
      params:
        - name: repo_url
          value: $(params.repo_url)
        - name: target_branch
          value: $(params.target_branch)
        - name: test_branch
          value: $(params.target_branch)
    - name: test-baseline
      taskRef:
        name: test-pipeline-service
      runAfter:
        - "deploy-pipeline-service-baseline"
      params:
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: workdir
          workspace: shared-workspace
    - name: upgrade-pipeline-service
      taskRef:
        name: deploy-pipeline-service
      runAfter:
        - "test-baseline"
      workspaces:
        - name: workdir
          workspace: shared-workspace
      params:
        - name: repo_url
          value: $(params.repo_url)
        - name: target_branch
          value: $(params.target_branch)
        - name: test_branch
          value: $(params.revision)
    - name: test-upgrade
      taskRef:
        name: test-pipeline-service
      runAfter:
        - "upgrade-pipeline-service"
      params:
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: workdir
          workspace: shared-workspace
    - name: downgrade-pipeline-service
      taskRef:
        name: deploy-pipeline-service
      runAfter:
        - "test-upgrade"
      workspaces:
        - name: workdir
          workspace: shared-workspace
      params:
        - name: repo_url
          value: $(params.repo_url)
        - name: target_branch
          value: $(params.target_branch)
        - name: test_branch
          value: $(params.target_branch)
    - name: test-downgrade
      taskRef:
        name: test-pipeline-service
      runAfter:
        - "downgrade-pipeline-service"
      params:
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: workdir
          workspace: shared-workspace
  finally:
    - name: destroy-cluster
      taskRef:
        name: destroy-cluster
      when:
        - input: "$(tasks.deploy-cluster.status)"
          operator: notin
          values: ["None", "Failed"]
      params:
        - name: cluster-name
          value: "$(tasks.generate-cluster-name.results.cluster-name)"
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: workdir
          workspace: shared-workspace
