---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: upgrade-tests
spec:
  params:
    - name: aws_region
    - name: ocp_version
    - name: repo_url
    - name: revision
    - name: target_branch
  timeouts:
    finally: "0h30m0s"
  workspaces:
    - name: source
    - name: upgrade-shared-workspace
  tasks:
    - name: clone-pipeline-service-git
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
    - name: generate-cluster-name
      taskRef:
        name: generate-cluster-name
    - name: deploy-cluster
      taskRef:
        name: deploy-cluster
      runAfter:
        - "generate-cluster-name"
        - "clone-pipeline-service-git"
      params:
        - name: ocp_version
          value: $(params.ocp_version)
        - name: region
          value: $(params.aws_region)
        - name: cluster-name
          value: "$(tasks.generate-cluster-name.results.cluster-name)"
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: output
          workspace: upgrade-shared-workspace
        - name: source
          workspace: source
    - name: setup-ci-runner
      taskRef:
        name: setup-ci-runner-container
      runAfter:
        - "deploy-cluster"
      params:
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: source
          workspace: source
        - name: kubeconfig-dir
          workspace: upgrade-shared-workspace
    - name: plnsvc-setup-baseline
      taskRef:
        name: pipeline-service-setup
      runAfter:
        - "setup-ci-runner"
      workspaces:
        - name: kubeconfig-dir
          workspace: upgrade-shared-workspace
        - name: source
          workspace: source
      params:
        - name: repo_url
          value: $(params.repo_url)
        - name: target_branch
          value: $(params.target_branch)
        - name: test_branch
          value: $(params.target_branch)
    - name: tests-baseline
      taskRef:
        name: pipeline-service-tests
      runAfter:
        - "plnsvc-setup-baseline"
      params:
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: kubeconfig-dir
          workspace: upgrade-shared-workspace
        - name: source
          workspace: source
    - name: plnsvc-setup-upgrade
      taskRef:
        name: pipeline-service-setup
      runAfter:
        - "tests-baseline"
      workspaces:
        - name: kubeconfig-dir
          workspace: upgrade-shared-workspace
        - name: source
          workspace: source
      params:
        - name: repo_url
          value: $(params.repo_url)
        - name: target_branch
          value: $(params.target_branch)
        - name: test_branch
          value: $(params.revision)
    - name: tests-upgrade
      taskRef:
        name: pipeline-service-tests
      runAfter:
        - "plnsvc-setup-upgrade"
      params:
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: kubeconfig-dir
          workspace: upgrade-shared-workspace
        - name: source
          workspace: source
    - name: plnsvc-setup-downgrade
      taskRef:
        name: pipeline-service-setup
      runAfter:
        - "tests-upgrade"
      workspaces:
        - name: kubeconfig-dir
          workspace: upgrade-shared-workspace
        - name: source
          workspace: source
      params:
        - name: repo_url
          value: $(params.repo_url)
        - name: target_branch
          value: $(params.target_branch)
        - name: test_branch
          value: $(params.target_branch)
    - name: tests-downgrade
      taskRef:
        name: pipeline-service-tests
      runAfter:
        - "plnsvc-setup-downgrade"
      params:
        - name: target_branch
          value: $(params.target_branch)
      workspaces:
        - name: kubeconfig-dir
          workspace: upgrade-shared-workspace
        - name: source
          workspace: source
  finally:
    - name: destroy-cluster
      taskRef:
        name: destroy-cluster
      when:
        - input: "$(tasks.deploy-cluster.status)"
          operator: notin
          values: ["None", "Failed"]
      params:
        - name: cluster-name
          value: "$(tasks.generate-cluster-name.results.cluster-name)"
        - name: target_branch
          value: $(params.target_branch)
        - name: region
          value: $(params.aws_region)
      workspaces:
        - name: output
          workspace: upgrade-shared-workspace
        - name: source
          workspace: source
