---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #
  # For now we'll use the official release directly rather than downloading
  # it and checking it in.
  #
  # To list available releases:
  #  curl -s https://storage.googleapis.com/tekton-releases/ | xq | grep -E 'chains/.*/release.yaml'
  #
  - https://storage.googleapis.com/tekton-releases/chains/previous/v0.14.0/release.yaml
  - chains-secrets-config.yaml
  - public-key.yaml

images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/chains/cmd/controller:v0.14.0
    newName: registry.redhat.io/openshift-pipelines/pipelines-chains-controller-rhel8
    newTag: v1.10.2-1

patches:
  # allow openshift-gitops to manage tekton-chains
  - target:
      kind: Namespace
      name: tekton-chains
    patch: |-
      - op: add
        path: "/metadata/labels"
        value:
          argocd.argoproj.io/managed-by: openshift-gitops
  # Add some chains configuration
  - path: chains-config.yaml
  #
  # Mount the chains cert volume and apply operator security standards
  - path: chains-controller-deployment.yaml
  - target:
      kind: Secret
      name: signing-secrets
      namespace: tekton-chains
    patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: signing-secrets
        namespace: tekton-chains
      $patch: delete
