---
apiVersion: v1
kind: Service
metadata:
  name: tekton-chains
  namespace: openshift-pipelines
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: tekton-chains
    app.kubernetes.io/component: metrics
    app: tekton-chains-controller
spec:
  ports:
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-chains
    app.kubernetes.io/component: controller
