# Solves https://issues.redhat.com/browse/PLNSRVCE-1620
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-pipelines
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
