---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: custom-operators
  namespace: openshift-marketplace
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  sourceType: grpc
  image: quay.io/openshift-pipeline/openshift-pipelines-pipelines-operator-bundle-container-index@sha256:7444d41ebe811a505866a99a92e24ca390677835dfdd597bed2e0b5d66780c5b
  displayName: custom-operators
  updateStrategy:
    registryPoll:
      interval: 30m
