---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: custom-operators
  namespace: openshift-marketplace
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  sourceType: grpc
  image: quay.io/openshift-pipeline/openshift-pipelines-pipelines-operator-bundle-container-index@sha256:8d37842772952972e981d3224cb87958837300ec438ec421649a46382f55caff
  displayName: custom-operators
  updateStrategy:
    registryPoll:
      interval: 30m
