---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: custom-operators
  namespace: openshift-marketplace
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  sourceType: grpc
  image: quay.io/openshift-pipeline/openshift-pipelines-pipelines-operator-bundle-container-index@sha256:beec206d5f9650173348c0d9db404faee6b791ec6d25a9ea3410a909a8e37187
  displayName: custom-operators
  updateStrategy:
    registryPoll:
      interval: 30m
