---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-pipeline-service
spec:
  params:
    - name: repo_url
    - name: target_branch
    - name: test_branch
  workspaces:
    - name: workdir
  steps:
    - name: run-plnsvc-setup
      image: quay.io/redhat-pipeline-service/ci-runner:$(params.target_branch)
      resources:
        requests:
          memory: 500Mi
          cpu: 300m
      workingDir: "$(workspaces.workdir.path)/source"
      env:
        - name: KUBECONFIG
          value: "$(workspaces.workdir.path)/.kube/config"
        - name: REPO_URL
          value: $(params.repo_url)
        - name: REPO_REVISION
          value: $(params.test_branch)
      command:
        - ci/images/ci-runner/hack/bin/run-plnsvc-setup.sh
