---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: destroy-existing-cluster
spec:
  params:
    - name: target_branch
    - name: region
      description: ocp cluster region where you want to provision
  workspaces:
    - name: workdir
  steps:
    - name: destroy
      image: quay.io/redhat-pipeline-service/ci-runner:$(params.target_branch)
      env:
        - name: ROSA_TOKEN
          valueFrom:
            secretKeyRef:
              name: plnsvc-ci-secret
              key: "PLNSVC_ROSA_TOKEN"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: plnsvc-ci-secret
              key: "PLNSVC_AWS_KEY_ID"
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: plnsvc-ci-secret
              key: "PLNSVC_AWS_KEY"
        - name: REGION
          value: "$(params.region)"
      workingDir: "$(workspaces.workdir.path)/source"
      command:
        - ci/images/ci-runner/hack/bin/cleanup-expired-clusters.sh
