---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: run-rhtap-e2e
spec:
  workspaces:
    - name: workdir
  params:
    - name: repo_url
    - name: revision
    - name: repo_owner
    - name: target_branch
  kind: ClusterTask
  steps:
    - name: run-e2e-test
      image: quay.io/redhat-pipeline-service/e2e-test-runner:$(params.target_branch)
      resources:
        limits:
          memory: 4Gi
        requests:
          memory: 500Mi
          cpu: 300m
      env:
        - name: KUBECONFIG
          value: "$(workspaces.workdir.path)/kubeconfig"
        - name: PIPELINE_PR_OWNER
          value: $(params.repo_owner)
        - name: PIPELINE_PR_SHA
          value: $(params.revision)
        - name: BW_CLIENTID
          valueFrom:
            secretKeyRef:
              name: hypershift-bitwarden
              key: "BW_CLIENTID"
        - name: BW_CLIENTSECRET
          valueFrom:
            secretKeyRef:
              name: hypershift-bitwarden
              key: "BW_CLIENTSECRET"
        - name: BW_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hypershift-bitwarden
              key: "BW_PASSWORD"
      workingDir: "$(workspaces.workdir.path)/source"
      command:
        - ci/images/e2e-test-runner/run-e2e-test.sh
