---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: setup-ci-runner-container
spec:
  params:
    - name: target_branch
  workspaces:
    - name: workdir
  steps:
    - name: create-ci-runner-container
      image: quay.io/redhat-pipeline-service/ci-runner:$(params.target_branch)
      resources:
        requests:
          memory: 500Mi
          cpu: 300m
      env:
        - name: KUBECONFIG
          value: "$(workspaces.workdir.path)/.kube/config"
      workingDir: "$(workspaces.workdir.path)/source"
      command:
        - ci/images/ci-runner/hack/bin/create-ci-runner-container.sh
    - name: copy-plnsvc-code
      image: quay.io/redhat-pipeline-service/ci-runner:$(params.target_branch)
      resources:
        requests:
          memory: 500Mi
          cpu: 300m
      env:
        - name: KUBECONFIG
          value: "$(workspaces.workdir.path)/.kube/config"
      workingDir: "$(workspaces.workdir.path)/source"
      command:
        - ci/images/ci-runner/hack/bin/copy-plnsvc-code.sh
