# This should be moved to the gitops folder and be synced by gitops
# to guarantee that there's no configuration drift between clusters.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "pac-manager-binding"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pac-admin
subjects:
  - kind: ServiceAccount
    name: pac-manager
    namespace: pipelines-as-code
