---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: o11y

configMapGenerator:
  - name: grafana-dashboard-pipeline-service
    files:
      - dashboards/pipeline-service-dashboard.json

resources:
  - dashboard.yaml
