---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-reader
  namespace: tekton-results
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-reader
  namespace: tekton-results
  annotations:
    kubernetes.io/service-account.name: metrics-reader
    argocd.argoproj.io/sync-wave: "0"
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-results-service-metrics-reader
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-tekton-results-service-metrics-reader
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-results-service-metrics-reader
subjects:
  - kind: ServiceAccount
    name: metrics-reader
    namespace: tekton-results
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tekton-results-api
  namespace: tekton-results
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  jobLabel: "app.kubernetes.io/name"
  endpoints:
    - path: /metrics
      port: metrics
      scheme: https
      bearerTokenSecret:
        name: "metrics-reader"
        key: token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/name: "tekton-results-api"
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tekton-results-watcher
  namespace: tekton-results
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  endpoints:
    - path: /metrics
      port: watchermetrics
      scheme: https
      bearerTokenSecret:
        name: "metrics-reader"
        key: token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/name: tekton-results-watcher
