---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tekton-results-config-logging
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  # Adjust zap-logger config according to ADR 6
  zap-logger-config: |
    {
      "level": "info",
      "development": false,
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "ts",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "msg",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "iso8601",
        "durationEncoder": "string",
        "callerEncoder": ""
      }
    }
  # Adjust logging level of the watcher and controller
  loglevel.watcher: info
  loglevel.controller: info
