resources:
- pod.yaml
- https://raw.githubusercontent.com/tektoncd/pipeline/v0.32.0/config/100-namespace.yaml
- https://raw.githubusercontent.com/tektoncd/pipeline/v0.32.0/config/300-condition.yaml
- https://raw.githubusercontent.com/tektoncd/pipeline/v0.32.0/config/300-pipelinerun.yaml
- https://raw.githubusercontent.com/tektoncd/pipeline/v0.32.0/config/300-resource.yaml
- https://raw.githubusercontent.com/tektoncd/pipeline/v0.32.0/config/300-run.yaml
- https://raw.githubusercontent.com/tektoncd/pipeline/v0.32.0/config/300-taskrun.yaml
- https://raw.githubusercontent.com/tektoncd/pipeline/v0.32.0/config/config-artifact-bucket.yaml
- https://raw.githubusercontent.com/tektoncd/pipeline/v0.32.0/config/config-artifact-pvc.yaml
- https://raw.githubusercontent.com/tektoncd/pipeline/v0.32.0/config/config-defaults.yaml
- https://raw.githubusercontent.com/tektoncd/pipeline/v0.32.0/config/config-feature-flags.yaml
- https://raw.githubusercontent.com/tektoncd/pipeline/v0.32.0/config/config-info.yaml
- https://raw.githubusercontent.com/tektoncd/pipeline/v0.32.0/config/config-leader-election.yaml
- https://raw.githubusercontent.com/tektoncd/pipeline/v0.32.0/config/config-logging.yaml
- https://raw.githubusercontent.com/tektoncd/pipeline/v0.32.0/config/config-observability.yaml
- https://raw.githubusercontent.com/tektoncd/pipeline/v0.32.0/config/config-registry-cert.yaml

# patches to resources in this environment
patches:
- patch: |-
    - op: add
      path: /data
      value: {'size': '5Gi'}
  target:
    kind: ConfigMap
    name: config-artifact-pvc
    namespace: tekton-pipelines
- patch: |-
    - op: replace
      path: /data/enable-tekton-oci-bundles
      value: 'true'
  target:
    kind: ConfigMap
    name: feature-flags
    namespace: tekton-pipelines
- patch: |-
    - op: remove
      path: /spec/conversion
  target:
    kind: CustomResourceDefinition
    name: pipelineruns.tekton.dev
- patch: |-
    - op: remove
      path: /spec/conversion
  target:
    kind: CustomResourceDefinition
    name: taskruns.tekton.dev


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
