---
apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  annotations: {}
  name: glbc
spec:
  permissionClaims:
    - group: ""
      resource: secrets
      state: Accepted
    - group: ""
      # TODO: identityHash needs to match the specific value in the glbc apiexport of the cluster
      identityHash: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      resource: services
      state: Accepted
    - group: apps
      # TODO: identityHash needs to match the specific value in the glbc apiexport of the cluster
      identityHash: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      resource: deployments
      state: Accepted
    - group: networking.k8s.io
      # TODO: identityHash needs to match the specific value in the glbc apiexport of the cluster
      identityHash: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      resource: ingresses
      state: Accepted
  reference:
    workspace:
      # TODO: exportName and path need to match the specific values of the cluster
      exportName: glbc-pipeline
      path: root:workspace-glbc
