---
# Remove signing-secrets so it does not conflicts with the existing immutable secret
# installed by operator/images/cluster-setup/install.sh
$patch: delete
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-chains
  name: signing-secrets
  namespace: tekton-chains
