---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tekton-results
  - https://github.com/owner/repository.git/path/gitops/argocd?ref=branch
patches:
  - path: patch-pipeline-service.yaml
  - path: patch-pipeline-service-storage.yaml
  - path: patch-pipeline-service-o11y.yaml
