---
resources:
  - ../../base

patchesStrategicMerge:
  - chains-secrets-config-patch.yaml
  - security-context-fix.yaml

patchesJson6902:
  - target:
      kind: RoleBinding
      name: grant-argocd
      namespace: tekton-chains
    patch: |-
      - op: replace
        path: /subjects/0/name
        value: openshift-gitops-argocd-application-controller
  - target:
      kind: RoleBinding
      name: grant-argocd
      namespace: tekton-chains
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: openshift-gitops
  - target:
      kind: Role
      name: secret-reader
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: openshift-ingress-operator
  - target:
      kind: RoleBinding
      name: chains-secret-reader
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: openshift-ingress-operator
