---
# This YAML file allows openshift_dev_setup.sh to fetch values of certain variables.
# Usage - to be used for overwriting defaults

# cluster_type can only be "openshift" for now.
cluster_type: openshift

# git_url refers to a git repo to be considered as the source of truth for Argo CD applications.
git_url: https://github.com/openshift-pipelines/pipeline-service.git

# git_ref refers to the git repo's ref to be considered as the source of truth for Argo CD applications.
git_ref: kcp

kcp:
  # crs_to_sync is a list of the CRs which need to be synced.
  crs_to_sync:
    - deployments.apps
    - services
    - ingresses.networking.k8s.io
    - networkpolicies.networking.k8s.io
    - pipelines.tekton.dev
    - pipelineruns.tekton.dev
    - tasks.tekton.dev
    - repositories.pipelinesascode.tekton.dev
  version: v0.9.0
  workspace: root:default:pipeline-service-compute

# Applications to be deployed on the cluster
apps:
  - pipeline_service # pipeline_service sets up Pipeline Service on the cluster.

# Tekton results database credentials
tekton_results_db:
  user:
  password:
