apiVersion: batch/v1
kind: Job
metadata:
  name: patch-tekton-config-parameters
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.10
          command:
            - /bin/bash
            - -c
            - |
              echo "Waiting for TektonConfig config to be present"
              until oc get TektonConfig config -n openshift-operators
              do
                sleep $SLEEP;
              done

              echo "Patching TektonConfig config patameters"
              oc patch TektonConfig config --type='json' -p='[{"op":"remove","path":"/spec/pruner/keep"},{"op":"add","path":"/spec/pruner/keep-since","value":2880},{"op":"replace","path":"/spec/pruner/resources/0","value":"taskrun"},{"op":"replace","path":"/spec/pipeline/enable-tekton-oci-bundles","value":true}]'
          imagePullPolicy: Always
          name: patch-tekton-config-parameters
          env:
            - name: SLEEP
              value: "5"
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30
      serviceAccount: openshift-gitops-argocd-application-controller
      serviceAccountName: openshift-gitops-argocd-application-controller
