---
apiVersion: batch/v1
kind: Job
metadata:
  name: chains-certs-configuration
  namespace: tekton-chains
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.11
          imagePullPolicy: Always
          name: patch-chains-certs
          command:
            - /bin/bash
            - -c
            - |
              ns=tekton-chains
              ca_crt="/tmp/ca-certificates.crt"

              echo "Waiting for secret and configmaps to be present"
              until oc get -n "$ns" secret chains-ca-cert && \
                oc get -n "$ns" cm config-trusted-cabundle && \
                oc get -n "$ns" cm kube-root-ca.crt
              do
                sleep 5;
              done

              # Update the chains-ca-cert secret with cluster certs, trusted-ca's and ingress cert.
              # The configmaps are injected by the Cluster Network Operator.
              echo "Build the new certificate"
              oc get -n "$ns" cm config-trusted-cabundle -o jsonpath="{.data.ca-bundle\.crt}" > "$ca_crt"
              oc get -n "$ns" cm kube-root-ca.crt -o jsonpath="{.data.ca\.crt}" >> "$ca_crt"
              oc get -n openshift-ingress-operator secret router-ca -o jsonpath="{.data.tls\.crt}" | base64 -d >> "$ca_crt"
              cat "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt" >> "$ca_crt"

              echo "Replace secret/chains-ca-cert"
              oc create -n "$ns" secret generic chains-ca-cert --from-file="$ca_crt" --dry-run=client -o yaml | oc replace -f -
