---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
  namespace: tekton-results
  labels:
    app: minio
  annotations:
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "0"
spec:
  image: quay.io/minio/minio:latest
  requestAutoCert: false
  podManagementPolicy: Parallel
  configuration:
    name: minio-configuration
  exposeServices:
    minio: true
  features:
    bucketDNS: false
  users:
    - name: minio-user
  buckets:
    - name: tekton-results
      region: not-applicable
      objectLock: true
  pools:
    - servers: 1
      name: pool-0
      volumesPerServer: 2
      volumeClaimTemplate:
        apiVersion: v1
        kind: persistentvolumeclaims
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
      securityContext:
        runAsNonRoot: true
      containerSecurityContext:
        runAsNonRoot: true
