---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-service-static-code-analysis
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[refs/heads/*]"
    pipelinesascode.tekton.dev/task: "[git-clone]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  timeouts:
    pipeline: "0h20m0s"
    tasks: "0h5m0s"
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: target_branch
      value: "{{ target_branch }}"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
      - name: target_branch
    workspaces:
      - name: source
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
          kind: ClusterTask
        workspaces:
          - name: output
            workspace: source
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
      - name: shellcheck
        runAfter:
          - fetch-repository
        workspaces:
          - name: source
            workspace: source
        params:
          - name: target_branch
            value: $(params.target_branch)
        taskSpec:
          params:
            - name: target_branch
          steps:
            - name: run-shellcheck
              image: quay.io/redhat-pipeline-service/static-checks:$(params.target_branch)
              imagePullPolicy: Always
              script: |
                #!/usr/bin/env bash
                /opt/static-checks/bin/shellcheck.sh --workspace_dir $(workspaces.source.path)
          workspaces:
            - name: source
      - name: yamllint
        runAfter:
          - fetch-repository
        workspaces:
          - name: source
            workspace: source
        params:
          - name: target_branch
            value: $(params.target_branch)
        taskSpec:
          params:
            - name: target_branch
          steps:
            - name: run-yamllint
              image: quay.io/redhat-pipeline-service/static-checks:$(params.target_branch)
              imagePullPolicy: Always
              script: |
                #!/usr/bin/env bash
                /opt/static-checks/bin/yamllint.sh --workspace_dir $(workspaces.source.path)
          workspaces:
            - name: source
      - name: hadolint
        runAfter:
          - fetch-repository
        workspaces:
          - name: source
            workspace: source
        params:
          - name: target_branch
            value: $(params.target_branch)
        taskSpec:
          params:
            - name: target_branch
          steps:
            - name: run-hadolint
              image: quay.io/redhat-pipeline-service/static-checks:$(params.target_branch)
              script: |
                #!/usr/bin/env bash
                /opt/static-checks/bin/hadolint.sh --workspace_dir $(workspaces.source.path)
          workspaces:
            - name: source
      - name: checkov
        runAfter:
          - fetch-repository
        workspaces:
          - name: source
            workspace: source
        params:
          - name: target_branch
            value: $(params.target_branch)
        taskSpec:
          params:
            - name: target_branch
          steps:
            - name: run-checkov
              image: quay.io/redhat-pipeline-service/static-checks:$(params.target_branch)
              script: |
                #!/usr/bin/env bash
                /opt/static-checks/bin/checkov.sh --workspace_dir $(workspaces.source.path)
          workspaces:
            - name: source
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
