---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test-pipeline-service-upgrade-ocp-414
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[refs/heads/*]"
    pipelinesascode.tekton.dev/pipeline: "[.tekton/pipeline/test-pipeline-service-upgrade.yaml]"
    pipelinesascode.tekton.dev/task: "[.tekton/tasks/setup-ci-runner-container.yaml]"
    pipelinesascode.tekton.dev/task-1: "[.tekton/tasks/deploy-cluster.yaml]"
    pipelinesascode.tekton.dev/task-2: "[.tekton/tasks/destroy-cluster.yaml]"
    pipelinesascode.tekton.dev/task-3: "[.tekton/tasks/generate-cluster-name.yaml]"
    pipelinesascode.tekton.dev/task-4: "[.tekton/tasks/deploy-pipeline-service.yaml]"
    pipelinesascode.tekton.dev/task-5: "[.tekton/tasks/test-pipeline-service.yaml]"
    pipelinesascode.tekton.dev/task-6: "[git-clone]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  pipelineRef:
    name: test-pipeline-service-upgrade
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: target_branch
      value: "{{ target_branch }}"
  timeouts:
    pipeline: "1h30m0s"
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
