---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-service-test
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "main"
    pipelinesascode.tekton.dev/task: "[git-clone]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: namespace
      value: "ci-clusters"
  timeouts:
    pipeline: "1h0m0s"
    finally: "0h20m0s"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
      - name: namespace
    workspaces:
      - name: source
      - name: kubeconfig-dir
      - name: hypershift-cluster-template
      - name: shared-workspace
    tasks:
      - name: produce-cluster-name
        taskSpec:
          results:
            - name: cluster-name
              description: Openshift cluster name
          steps:
            - name: cluster-name
              image: registry.access.redhat.com/ubi9/openssl:9.1-2
              script: |
                #!/usr/bin/env bash
                set -o errexit
                set -o nounset
                set -o pipefail
                set -x
                CLUSTER_NAME="ci-$( openssl rand -hex 5 )"
                echo -n "$CLUSTER_NAME" | tee $(results.cluster-name.path)
      - name: deploy-cluster
        runAfter:
          - "produce-cluster-name"
        params:
          - name: image
            value: "quay.io/openshift-release-dev/ocp-release:4.11.16-x86_64"
          - name: region
            value: "us-east-1"
          - name: cluster-name
            value: "$(tasks.produce-cluster-name.results.cluster-name)"
          - name: namespace
            value: "$(params.namespace)"
        workspaces:
          - name: kubeconfig-dir
            workspace: kubeconfig-dir
          - name: hypershift-cluster-template
            workspace: hypershift-cluster-template
          - name: output
            workspace: shared-workspace
        taskSpec:
          params:
            - name: region
            - name: cluster-name
            - name: image
            - name: namespace
          results:
            - name: kubeconfig
              description: the kubeconfig content of the new OCP cluster
          workspaces:
            - name: kubeconfig-dir
            - name: hypershift-cluster-template
            - name: output
              description: The kubeconfig of new cluster will be stored onto the volume backing this Workspace
          kind: ClusterTask
          steps:
            - name: generate-hypershift-deployment
              image: ghcr.io/sharkusmanch/envsubst:1.2.0
              env:
                - name: REGION
                  value: "$(params.region)"
                - name: CLUSTER_NAME
                  value: "$(params.cluster-name)"
                - name: IMAGE
                  value: "$(params.image)"
              script: |
                envsubst < $(workspaces.hypershift-cluster-template.path)/cluster-template.yaml | tee $(workspaces.output.path)/hypershift_deployment.yaml
            - name: deploy-cluster
              image: quay.io/redhat-pipeline-service/ci-runner:main
              imagePullPolicy:  Always
              script: |
                #!/usr/bin/env bash
                set -o errexit
                set -o nounset
                set -o pipefail
                set -x

                export KUBECONFIG=$(workspaces.kubeconfig-dir.path)/kubeconfig
                kubectl -n $(params.namespace) apply -f $(workspaces.output.path)/hypershift_deployment.yaml
                echo "Wait until hypershift cluster is ready..."
                wait_period=0
                while [[ "$(kubectl -n $(params.namespace) get hypershiftdeployment $(params.cluster-name) -o json | jq -r '.status.conditions[]? | select(.type == "HostedClusterProgress") | .reason')" != "Completed" ]]
                do
                  if [ "$wait_period" -gt 1200 ]; then
                    echo "[ERROR] Failed to create OCP cluster." >&2
                    kubectl -n $(params.namespace) get hypershiftdeployment $(params.cluster-name) -o yaml
                    exit 1
                  fi
                  sleep 60
                  wait_period=$((wait_period + 60))
                  echo "Waited $wait_period seconds..."
                done

                echo "Hypershift is ready, the following is the cluster kubeconfig"
                kubectl get secret -n clusters "$(params.cluster-name)-admin-kubeconfig" -o json | jq -r '.data.kubeconfig'  | base64 -d | tee $(workspaces.output.path)/kubeconfig
      - name: fetch-repository
        runAfter:
          - "deploy-cluster"
        taskRef:
          name: git-clone
          kind: ClusterTask
        workspaces:
          - name: output
            workspace: source
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
      - name: setup-ci-runner-container
        runAfter:
          - "fetch-repository"
        retries: 1
        workspaces:
          - name: source
            workspace: source
          - name: kubeconfig-dir
            workspace: shared-workspace
        taskSpec:
          workspaces:
            - name: source
            - name: kubeconfig-dir
          kind: ClusterTask
          steps:
            - name: create-ci-runner-container
              image: quay.io/redhat-pipeline-service/ci-runner:main
              resources:
                requests:
                  memory: 500Mi
                  cpu: 300m
              script: |
                #!/usr/bin/env bash
                set -o errexit
                set -o nounset
                set -o pipefail
                set -x

                export KUBECONFIG=$(workspaces.kubeconfig-dir.path)/kubeconfig

                kubectl -n openshift-config get secret/pull-secret -o yaml > /tmp/pull-secret.yaml
                yq -i '.metadata.namespace="default" | del(.type) | del(.metadata.uid) | del(.metadata.resourceVersion) | .data.["auth.json"]=.data.[".dockerconfigjson"] | del(.data.[".dockerconfigjson"])' /tmp/pull-secret.yaml
                kubectl -n default apply -f /tmp/pull-secret.yaml

                kubectl -n default apply -f - <<EOF
                apiVersion: v1
                kind: PersistentVolumeClaim
                metadata:
                  name: ci-runner-pvc
                spec:
                  accessModes:
                    - ReadWriteOnce
                  storageClassName: gp2
                  resources:
                    requests:
                      storage: 5Gi
                EOF

                kubectl -n default apply -f - <<EOF
                apiVersion: v1
                kind: Pod
                metadata:
                  name: ci-runner
                spec:
                  containers:
                  - name: ci-runner
                    image: quay.io/redhat-pipeline-service/ci-runner:main
                    imagePullPolicy:  Always
                    resources:
                      requests:
                        ephemeral-storage: "2Gi"
                      limits:
                        ephemeral-storage: "2Gi"
                    command:
                    - /bin/bash
                    - -c
                    - sleep 3600
                    securityContext:
                      privileged: true
                    volumeMounts:
                    - name: pull-secret
                      mountPath: "/run/user/0/containers/"
                      readOnly: true
                    - name: ci-runner-storage
                      mountPath: "/source"
                  volumes:
                  - name: pull-secret
                    secret:
                      secretName: pull-secret
                  - name: ci-runner-storage
                    persistentVolumeClaim:
                      claimName: ci-runner-pvc
                EOF

                kubectl -n default wait pod/ci-runner --for=condition=Ready --timeout=90s
                kubectl -n default describe pod/ci-runner
            - name: copy-plnsvc-code
              image: quay.io/redhat-pipeline-service/ci-runner:main
              resources:
                requests:
                  memory: 500Mi
                  cpu: 300m
              workingDir: "$(workspaces.source.path)"
              script: |
                #!/usr/bin/env bash
                set -o errexit
                set -o nounset
                set -o pipefail
                set -x

                export KUBECONFIG=$(workspaces.kubeconfig-dir.path)/kubeconfig
                echo "Copy source code of pipeline service to the ci-runner container"
                kubectl cp ./ default/ci-runner:/source

                echo "Copy new cluster's kubeconfig to the ci-runner container"
                kubectl cp "$KUBECONFIG" default/ci-runner:/kubeconfig
      - name: plnsvc-setup
        runAfter:
          - "setup-ci-runner-container"
        retries: 1
        workspaces:
          - name: kubeconfig-dir
            workspace: shared-workspace
          - name: source
            workspace: source
        params:
          - name: repo_url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
        taskSpec:
          workspaces:
            - name: kubeconfig-dir
            - name: source
          params:
            - name: repo_url
            - name: revision
          kind: ClusterTask
          steps:
            - name: run-plnsvc-setup
              image: quay.io/redhat-pipeline-service/ci-runner:main
              resources:
                requests:
                  memory: 500Mi
                  cpu: 300m
              workingDir: "$(workspaces.source.path)"
              script: |
                #!/usr/bin/env bash
                set -o errexit
                set -o nounset
                set -o pipefail
                set -x
                echo "Produce a plnsvc_setup.sh with the execution of script dev_setup.sh"
                cat <<'EOF' > plnsvc_setup.sh
                #!/usr/bin/env bash
                set -o errexit
                set -o nounset
                set -o pipefail

                export KUBECONFIG="/kubeconfig"
                OPENSHIFT_DIR=$(find "$PWD" -type f -name dev_setup.sh -exec dirname {} +)
                CONFIG="$OPENSHIFT_DIR/../config.yaml"
                echo "Start executing pipeline-service setup ..."
                yq -i e '.git_url="$(params.repo_url)"' "$CONFIG"
                yq -i e '.git_ref="$(params.revision)"' "$CONFIG"

                $OPENSHIFT_DIR/dev_setup.sh -d
                EOF

                chmod +x plnsvc_setup.sh
                export KUBECONFIG=$(workspaces.kubeconfig-dir.path)/kubeconfig
                echo "Copy plnsvc_setup.sh to the ci-runner pod ..."
                kubectl cp ./plnsvc_setup.sh default/ci-runner:/source

                echo "Execute dev_setup.sh script to set up pipeline-service ..."
                kubectl -n default exec pod/ci-runner -- sh -c "/source/plnsvc_setup.sh"
      - name: tests
        runAfter:
          - "plnsvc-setup"
        retries: 1
        workspaces:
          - name: kubeconfig-dir
            workspace: shared-workspace
          - name: source
            workspace: source
        taskSpec:
          workspaces:
            - name: kubeconfig-dir
            - name: source
          kind: ClusterTask
          steps:
            - name: run-tests
              image: quay.io/redhat-pipeline-service/ci-runner:main
              resources:
                requests:
                  memory: 500Mi
                  cpu: 300m
              workingDir: "$(workspaces.source.path)"
              script: |
                #!/usr/bin/env bash
                set -o errexit
                set -o nounset
                set -o pipefail
                set -x

                export KUBECONFIG=$(workspaces.kubeconfig-dir.path)/kubeconfig

                echo "Produce a plnsvc_test.sh with the execution of script test.sh"
                cat <<'EOF' > plnsvc_test.sh
                #!/usr/bin/env bash
                set -o errexit
                set -o nounset
                set -o pipefail
                set -x

                export KUBECONFIG="/kubeconfig"

                echo "Start executing pipeline cases ..."
                TEST_DIR=$(find "$PWD" -type f -name test.sh -exec dirname {} +)
                CASES=pipelines $TEST_DIR/test.sh
                EOF

                chmod +x plnsvc_test.sh

                echo "Copy plnsvc_test.sh to the ci-runner pod ..."
                kubectl cp plnsvc_test.sh default/ci-runner:/source

                echo "Execute test.sh script to verify pipeline-service ..."
                kubectl -n default exec pod/ci-runner -- sh -c "/source/plnsvc_test.sh"
    finally:
      - name: destroy-cluster
        params:
          - name: deploy-cluster-status
            value: "$(tasks.deploy-cluster.status)"
          - name: plnsvc-setup-status
            value: "$(tasks.plnsvc-setup.status)"
          - name: tests-status
            value: "$(tasks.tests.status)"
          - name: namespace
            value: "$(params.namespace)"
          - name: cluster-name
            value: "$(tasks.produce-cluster-name.results.cluster-name)"
        workspaces:
          - name: kubeconfig-dir
            workspace: kubeconfig-dir
        taskSpec:
          params:
            - name: deploy-cluster-status
            - name: plnsvc-setup-status
            - name: tests-status
            - name: namespace
            - name: cluster-name
          workspaces:
            - name: kubeconfig-dir
          kind: ClusterTask
          steps:
            - name: destroy
              image: quay.io/redhat-pipeline-service/ci-runner:main
              script: |
                #!/usr/bin/env bash
                set -o errexit
                set -o nounset
                set -o pipefail
                set -x

                export KUBECONFIG=$(workspaces.kubeconfig-dir.path)/kubeconfig

                if [[ "$(params.deploy-cluster-status)" != "None" ]]; then
                  echo "Started to destroy cluster [$(params.cluster-name)]..."
                  kubectl -n $(params.namespace) delete HypershiftDeployment $(params.cluster-name)
                  echo "Successfully destroyed cluster"
                else
                  echo "No OCP cluster need to be destroyed."
                fi
  workspaces:
    - name: kubeconfig-dir
      configMap:
        name: kubeconfig
    - name: hypershift-cluster-template
      configMap:
        name: hypershift-cluster-template
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Mi
