---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test-pipeline-service-static-code-analysis
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[refs/heads/*]"
    pipelinesascode.tekton.dev/task: "[git-clone]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  timeouts:
    pipeline: "0h20m0s"
    tasks: "0h5m0s"
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: target_branch
      value: "{{ target_branch }}"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
      - name: target_branch
    workspaces:
      - name: shared-workspace
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
          kind: ClusterTask
        workspaces:
          - name: output
            workspace: shared-workspace
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
          - name: subdirectory
            value: source
      - name: shellcheck
        runAfter:
          - fetch-repository
        workspaces:
          - name: workdir
            workspace: shared-workspace
        params:
          - name: target_branch
            value: $(params.target_branch)
        taskSpec:
          params:
            - name: target_branch
          steps:
            - name: run-shellcheck
              image: quay.io/redhat-pipeline-service/static-checks:$(params.target_branch)
              imagePullPolicy: Always
              workingDir: $(workspaces.workdir.path)/source
              script: |
                #!/usr/bin/env bash
                ci/images/static-checks/content/bin/shellcheck.sh \
                  --workspace_dir .
          workspaces:
            - name: workdir
      - name: yamllint
        runAfter:
          - fetch-repository
        workspaces:
          - name: workdir
            workspace: shared-workspace
        params:
          - name: target_branch
            value: $(params.target_branch)
        taskSpec:
          params:
            - name: target_branch
          steps:
            - name: run-yamllint
              image: quay.io/redhat-pipeline-service/static-checks:$(params.target_branch)
              imagePullPolicy: Always
              workingDir: $(workspaces.workdir.path)/source
              script: |
                #!/usr/bin/env bash
                ci/images/static-checks/content/bin/yamllint.sh \
                  --config-file ./ci/images/static-checks/content/config/yamllint.yaml \
                  --workspace_dir .
          workspaces:
            - name: workdir
      - name: hadolint
        runAfter:
          - fetch-repository
        workspaces:
          - name: workdir
            workspace: shared-workspace
        params:
          - name: target_branch
            value: $(params.target_branch)
        taskSpec:
          params:
            - name: target_branch
          steps:
            - name: run-hadolint
              image: quay.io/redhat-pipeline-service/static-checks:$(params.target_branch)
              workingDir: $(workspaces.workdir.path)/source
              script: |
                #!/usr/bin/env bash
                ci/images/static-checks/content/bin/hadolint.sh \
                  --config-file ./ci/images/static-checks/content/config/hadolint.yaml \
                  --workspace_dir .
          workspaces:
            - name: workdir
      - name: checkov
        runAfter:
          - fetch-repository
        workspaces:
          - name: workdir
            workspace: shared-workspace
        params:
          - name: target_branch
            value: $(params.target_branch)
        taskSpec:
          params:
            - name: target_branch
          steps:
            - name: run-checkov
              image: quay.io/redhat-pipeline-service/static-checks:$(params.target_branch)
              workingDir: $(workspaces.workdir.path)/source
              script: |
                #!/usr/bin/env bash
                ci/images/static-checks/content/bin/checkov.sh \
                  --config-file ./ci/images/static-checks/content/config/checkov.yaml \
                  --workspace_dir .
          workspaces:
            - name: workdir
      - name: grafana-dashboards
        runAfter:
          - fetch-repository
        workspaces:
          - name: workdir
            workspace: shared-workspace
        params:
          - name: target_branch
            value: $(params.target_branch)
        taskSpec:
          params:
            - name: target_branch
          steps:
            - name: run-grafana-dashboards
              image: quay.io/redhat-pipeline-service/static-checks:$(params.target_branch)
              imagePullPolicy: Always
              workingDir: $(workspaces.workdir.path)/source
              script: |
                #!/usr/bin/env bash
                ci/images/static-checks/content/bin/grafana-dashboards.sh
                  --workspace_dir ./operator/gitops/argocd/grafana/dashboards
          workspaces:
            - name: workdir
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
