---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-service-update-dependencies
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[refs/heads/*]"
    pipelinesascode.tekton.dev/task: "[git-clone]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  timeouts:
    pipeline: "0h20m0s"
    tasks: "0h5m0s"
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
    workspaces:
      - name: source
    tasks:
      - name: clone-repository
        taskRef:
          name: git-clone
          kind: ClusterTask
        workspaces:
          - name: output
            workspace: source
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
      - name: update-dockerfiles
        runAfter:
          - clone-repository
        workspaces:
          - name: source
            workspace: source
        params:
          - name: revision
            value: $(params.revision)
        taskSpec:
          params:
            - name: revision
              value: $(params.revision)
          steps:
            - name: setup-local-repository
              image: quay.io/rarnaud/dependencies-update:latest
              imagePullPolicy: Always
              script: |
                #!/usr/bin/env bash
                set -o errexit
                set -o pipefail
                set -x
                cd "$(workspaces.source.path)"

                # Setup user
                git config --local user.email "pipeline-service@example.com"
                git config --local user.name "Pipeline Service Robot"

                # Use SSH authentication
                git config --replace-all remote.origin.url "$(
                  git config --get remote.origin.url | \
                    sed -e "s|^https\?://github.com/|git@github.com:|" -e "s|\(\.git\)\?$|.git|"
                )"
                ln -f -s /tekton/home/.ssh "$HOME"
                ls -la "$HOME"
                ls -la "$HOME/.ssh/"

                # Set the branch
                # BRANCH_NAME="$(params.revision)"
                BRANCH_NAME="tetkon-workflow"
                git checkout -b "$BRANCH_NAME"
            - name: update-dockerfiles
              image: quay.io/rarnaud/dependencies-update:latest
              imagePullPolicy: Always
              script: |
                #!/usr/bin/env bash
                # TODO: Validate that the push to the git repo works
                set -o errexit
                set -o pipefail
                set -x
                cd "$(workspaces.source.path)"
                /opt/dependencies-update/bin/update.sh \
                  --commit_to "robot/$(git branch --show-current)/update_dockerfiles" \
                  --task update_dockerfiles_base_images_sha \
                  --workspace_dir "$(workspaces.source.path)"
          workspaces:
            - name: source
      # TODO: Enable PR creation
      # - name: open-pr-update-dockerfiles
      #   runAfter:
      #     - update-dockerfiles
      #   taskRef:
      #     name: github-open-pr
      #     kind: ClusterTask
      #   workspaces:
      #     - name: output
      #       workspace: source
      #   params:
      #     - name: REPO_FULL_NAME
      #       # This value is most likely wrong
      #       value: $(params.repo_url)
      #     - name: BASE
      #       value: $(params.revision)
      #     - name: HEAD
      #       value: robot/$(params.revision)/update-dockerfiles
      #     - name: BODY
      #       value: Generated by developer/images/dependencies-update/content/bin/update.sh
      #     - name: TITLE
      #       value: Update Dockerfiles
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
