---
apiVersion: batch/v1
kind: Job
metadata:
  name: tekton-chains-signing-secret
  namespace: openshift-pipelines
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation  # Delete the job so it can be recreated and updated during the sync.
spec:
  template:
    spec:
      containers:
        - name: chains-secret-generation
          image: quay.io/redhat-appstudio/appstudio-utils:dbbdd82734232e6289e8fbae5b4c858481a7c057
          imagePullPolicy: Always
          command:
            - /bin/bash
            - -c
            - |
              set -o errexit
              set -o nounset
              set -o pipefail

              namespace="openshift-pipelines"
              secret="signing-secrets"

              if [ "$(kubectl get secret "$secret" -n "$namespace" -o jsonpath='{.data}' --ignore-not-found --allow-missing-template-keys)" != "" ]; then
                echo "Signing secret exists and is non-empty."
              else
                # Delete secret/signing-secrets if already exists since by default cosign creates immutable secrets
                kubectl delete secrets "$secret" -n "$namespace" --ignore-not-found=true

                # To make this run conveniently without user input let's create a random password
                RANDOM_PASS=$( openssl rand -base64 30 )

                # Generate the key pair secret directly in the cluster.
                echo "Generating k8s secret/$secret in $namespace with key-pair"
                env COSIGN_PASSWORD=$RANDOM_PASS cosign generate-key-pair "k8s://$namespace/$secret"
              fi
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 250Mi
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30
      serviceAccount: chains-secrets-admin
      serviceAccountName: chains-secrets-admin
