---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio
  namespace: tekton-results
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minio
  namespace: tekton-results
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - nonroot
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minio
  namespace: tekton-results
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: minio
subjects:
  - kind: ServiceAccount
    name: minio
    namespace: tekton-results
