---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../operator/gitops/argocd/pipeline-service/tekton-results/base

patchesStrategicMerge:
  - minio-tls-patch.yaml
  - minio-user-cred-patch.yaml
  - s3-configuration-patch.yaml
