---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../operator/gitops/argocd/pipeline-service/tekton-results/base

patches:
  - path: minio-create-bucket.yaml
  - path: minio-tls.yaml
