---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apibinding:kubernetes:all-users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apibinding:kubernetes
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:authenticated
