---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - repository.yaml
  - https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-clone/0.9/git-clone.yaml
  - https://raw.githubusercontent.com/tektoncd/catalog/main/task/github-open-pr/0.2/github-open-pr.yaml

patches:
  - patch: |-
      - op: replace
        path: /kind
        value: ClusterTask
    target:
      kind: Task
      name: git-clone
  - patch: |-
      - op: replace
        path: /kind
        value: ClusterTask
    target:
      kind: Task
      name: github-open-pr
