# Generate the secret with
# (
#   TMPDIR=$(mktemp -d) \
#   && ssh-keygen \
#     -f "$TMPDIR/id_ed25519" \
#     -q \
#     -t ed25519 \
#     -C "pipeline-service-ci" \
#     -N "" \
#   && echo \
#   && echo "ssh-privatekey: |-" \
#   && echo "    $(cat "$TMPDIR/id_ed25519" | base64 | tr -d '\n')" \
#   && echo \
#   && echo "github deploy key:" \
#   && echo "    $(cat "$TMPDIR/id_ed25519.pub")" \
#   && rm -rf "$TMPDIR"
# )
# Then edit the 'pipeline' serviceaccount in the 'pipeline-service' namespace to
# add the 'ssh-key' secret.
#
# Don't forget to register the key in GitHub (https://github.com/openshift-pipelines/pipeline-service/settings/keys).
---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-key
  namespace: pipeline-service-ci
  annotations:
    tekton.dev/git-0: github.com # Described below
type: kubernetes.io/ssh-auth
stringData:
  known_hosts: |-
    github.com,140.82.112.3 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
data:
  ssh-privatekey: |-
---
# Generate a fine-grained token with r/w access to pull requests (https://github.com/settings/tokens?type=beta).
apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: pipeline-service-ci
stringData:
  token: |-
