---
name: Fetch security scan results from quay
on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Build and push images to quay"
    branches:
      - main
    types:
      - completed

jobs:
  scans:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      access-setup-output: ${{ steps.access-setup-scan.outputs.VULNERABILITIES_EXIST }}
      cluster-setup-output: ${{ steps.cluster-setup-scan.outputs.VULNERABILITIES_EXIST }}
      devenv-output: ${{ steps.devenv-scan.outputs.VULNERABILITIES_EXIST }}
      kcp-registrar-output: ${{ steps.kcp-registrar-scan.outputs.VULNERABILITIES_EXIST }}
      quay-upload-output: ${{ steps.quay-upload-scan.outputs.VULNERABILITIES_EXIST }}
      shellcheck-output: ${{ steps.shellcheck-scan.outputs.VULNERABILITIES_EXIST }}
      update-pipeline-service-output: ${{ steps.update-pipeline-service-scan.outputs.VULNERABILITIES_EXIST }}
      vulnerability-scan-output: ${{ steps.vulnerability-scan.outputs.VULNERABILITIES_EXIST }}
      yamllint-scan-output: ${{ steps.yamllint-scan.outputs.VULNERABILITIES_EXIST }}
    steps:
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            access-setup:
              - 'operator/images/access-setup/**'
            cluster-setup:
              - 'operator/images/cluster-setup/**'
            devenv:
              - 'developer/images/devenv/**'
            kcp-registrar:
              - 'operator/images/kcp-registrar/**'
            quay-upload:
              - 'ci/quay-upload/**'
            shellcheck:
              - 'ci/images/shellcheck/**'
            update-pipeline-service:
              - 'operator/images/update-pipeline-service/**'
            vulnerability:
              - 'ci/images/vulnerability-scan/**'
            yamllint:
              - 'ci/images/yamllint/**'

      - name: access-setup scan
        continue-on-error: true
        id: access-setup-scan
        if: steps.filter.outputs.access-setup == 'true'
        run: |
          ./ci/images/vulnerability-scan/scan-image.sh | tee /tmp/clair-scan.log
          echo "VULNERABILITIES_EXIST=$(tail -1 /tmp/clair-scan.log)" >> $GITHUB_OUTPUT
        env:
          AUTH_BEARER_TOKEN: ${{ secrets.AUTH_BEARER_TOKEN }}
          IMAGE_NAME: access-setup

      - name: cluster-setup scan
        continue-on-error: true
        id: cluster-setup-scan
        if: steps.filter.outputs.cluster-setup == 'true'
        run: |
          ./ci/images/vulnerability-scan/scan-image.sh | tee /tmp/clair-scan.log
          echo "VULNERABILITIES_EXIST=$(tail -1 /tmp/clair-scan.log)" >> $GITHUB_OUTPUT
        env:
          AUTH_BEARER_TOKEN: ${{ secrets.AUTH_BEARER_TOKEN }}
          IMAGE_NAME: cluster-setup

      - name: devenv scan
        continue-on-error: true
        id: devenv-scan
        if: steps.filter.outputs.devenv == 'true'
        run: |
          ./ci/images/vulnerability-scan/scan-image.sh | tee /tmp/clair-scan.log
          echo "VULNERABILITIES_EXIST=$(tail -1 /tmp/clair-scan.log)" >> $GITHUB_OUTPUT
        env:
          AUTH_BEARER_TOKEN: ${{ secrets.AUTH_BEARER_TOKEN }}
          IMAGE_NAME: devenv

      - name: kcp-registrar scan
        continue-on-error: true
        id: kcp-registrar-scan
        if: steps.filter.outputs.kcp-registrar == 'true'
        run: |
          ./ci/images/vulnerability-scan/scan-image.sh | tee /tmp/clair-scan.log
          echo "VULNERABILITIES_EXIST=$(tail -1 /tmp/clair-scan.log)" >> $GITHUB_OUTPUT
        env:
          AUTH_BEARER_TOKEN: ${{ secrets.AUTH_BEARER_TOKEN }}
          IMAGE_NAME: kcp-registrar

      - name: quay-upload scan
        continue-on-error: true
        id: quay-upload-scan
        if: steps.filter.outputs.quay-upload == 'true'
        run: |
          ./ci/images/vulnerability-scan/scan-image.sh | tee /tmp/clair-scan.log
          echo "VULNERABILITIES_EXIST=$(tail -1 /tmp/clair-scan.log)" >> $GITHUB_OUTPUT
        env:
          AUTH_BEARER_TOKEN: ${{ secrets.AUTH_BEARER_TOKEN }}
          IMAGE_NAME: quay-upload

      - name: shellcheck scan
        continue-on-error: true
        id: shellcheck-scan
        if: steps.filter.outputs.shellcheck == 'true'
        run: |
          ./ci/images/vulnerability-scan/scan-image.sh | tee /tmp/clair-scan.log
          echo "VULNERABILITIES_EXIST=$(tail -1 /tmp/clair-scan.log)" >> $GITHUB_OUTPUT
        env:
          AUTH_BEARER_TOKEN: ${{ secrets.AUTH_BEARER_TOKEN }}
          IMAGE_NAME: shellcheck

      - name: update-pipeline-service scan
        continue-on-error: true
        id: update-pipeline-service-scan
        if: steps.filter.outputs.update-pipeline-service == 'true'
        run: |
          ./ci/images/vulnerability-scan/scan-image.sh | tee /tmp/clair-scan.log
          echo "VULNERABILITIES_EXIST=$(tail -1 /tmp/clair-scan.log)" >> $GITHUB_OUTPUT
        env:
          AUTH_BEARER_TOKEN: ${{ secrets.AUTH_BEARER_TOKEN }}
          IMAGE_NAME: update-pipeline-service

      - name: vulnerability scan
        continue-on-error: true
        id: vulnerability-scan
        if: steps.filter.outputs.vulnerability == 'true'
        run: |
          ./ci/images/vulnerability-scan/scan-image.sh | tee /tmp/clair-scan.log
          echo "VULNERABILITIES_EXIST=$(tail -1 /tmp/clair-scan.log)" >> $GITHUB_OUTPUT
        env:
          AUTH_BEARER_TOKEN: ${{ secrets.AUTH_BEARER_TOKEN }}
          IMAGE_NAME: vulnerability-scan

      - name: yamllint scan
        continue-on-error: true
        id: yamllint-scan
        if: steps.filter.outputs.yamllint == 'true'
        run: |
          ./ci/images/vulnerability-scan/scan-image.sh | tee /tmp/clair-scan.log
          echo "VULNERABILITIES_EXIST=$(tail -1 /tmp/clair-scan.log)" >> $GITHUB_OUTPUT
        env:
          AUTH_BEARER_TOKEN: ${{ secrets.AUTH_BEARER_TOKEN }}
          IMAGE_NAME: yamllint

  check-results:
    runs-on: ubuntu-latest
    needs: scans
    if: always()
    steps:
      - name: Check access setup results
        id: check-access-setup-results
        if: always()
        run: |
          res=${{ needs.scans.outputs.access-setup-output }}
          res=${res:=0}
          if [[ $res != 0 ]]; then
            echo "Vulnerabilities found with access-setup image. Please check scans job for more details."
            exit 1
          else
            echo "No vulnerabilities found"
          fi

      - name: Check cluster setup results
        id: check-cluster-setup-results
        if: always()
        run: |
          res=${{ needs.scans.outputs.cluster-setup-output }}
          res=${res:=0}
          if [[ $res != 0 ]]; then
            echo "Vulnerabilities found with cluster-setup image. Please check scans job for more details."
            exit 1
          else
            echo "No vulnerabilities found"
          fi

      - name: Check devenv results
        id: check-devenv-results
        if: always()
        run: |
          res=${{ needs.scans.outputs.devenv-output }}
          res=${res:=0}
          if [[ $res != 0 ]]; then
            echo "Vulnerabilities found with devenv image. Please check scans job for more details."
            exit 1
          else
            echo "No vulnerabilities found"
          fi

      - name: Check kcp registrar results
        id: check-kcp-registrar-results
        if: always()
        run: |
          res=${{ needs.scans.outputs.kcp-registrar-output }}
          res=${res:=0}
          if [[ $res != 0 ]]; then
            echo "Vulnerabilities found with kcp-registrar image. Please check scans job for more details."
            exit 1
          else
            echo "No vulnerabilities found"
          fi

      - name: Check quay upload results
        id: check-quay-upload-results
        if: always()
        run: |
          res=${{ needs.scans.outputs.quay-upload-output }}
          res=${res:=0}
          if [[ $res != 0 ]]; then
            echo "Vulnerabilities found with quay-upload image. Please check scans job for more details."
            exit 1
          else
            echo "No vulnerabilities found"
          fi

      - name: Check shellcheck results
        id: check-shellcheck-results
        if: always()
        run: |
          res=${{ needs.scans.outputs.shellcheck-output }}
          res=${res:=0}
          if [[ $res != 0 ]]; then
            echo "Vulnerabilities found with shellcheck image. Please check scans job for more details."
            exit 1
          else
            echo "No vulnerabilities found"
          fi

      - name: Check update pipeline service results
        id: check-update-pipeline-service-results
        if: always()
        run: |
          res=${{ needs.scans.outputs.update-pipeline-service-output }}
          res=${res:=0}
          if [[ $res != 0 ]]; then
            echo "Vulnerabilities found with update-pipeline-service image. Please check scans job for more details."
            exit 1
          else
            echo "No vulnerabilities found"
          fi

      - name: Check vulnerability-scan results
        id: check-vulnerability-scan-results
        if: always()
        run: |
          res=${{ needs.scans.outputs.vulnerability-scan-output }}
          res=${res:=0}
          if [[ $res != 0 ]]; then
            echo "Vulnerabilities found with vulnerability-scan image. Please check scans job for more details."
            exit 1
          else
            echo "No vulnerabilities found"
          fi

      - name: Check yamllint results
        id: check-yamllint-results
        if: always()
        run: |
          res=${{ needs.scans.outputs.yamllint-output }}
          res=${res:=0}
          if [[ $res != 0 ]]; then
            echo "Vulnerabilities found with yamllint image. Please check scans job for more details."
            exit 1
          else
            echo "No vulnerabilities found"
          fi
