---
apiVersion: v1
data:
  POSTGRES_DB: tekton_results
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: tekton-results-database
    app.kubernetes.io/part-of: tekton-results
    app.kubernetes.io/version: v0.4.0
  name: tekton-results-database
  namespace: tekton-results
