---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - allow-argocd-to-manage.yaml
  - permissions.yaml
  - service-account.yaml
  - configmap.yaml
  - cert.yaml
  - route.yaml
  - deployment.yaml
